=== sevastyanovii/glnew-sql4/glnew-sql-module/src/main/java/ru/rbt/sqlmodule/parse/xjc/table-definition.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema targetNamespace="www.sqlpatchbuilder.org/table"
            xmlns="www.sqlpatchbuilder.org/table"
            xmlns:xs="http://www.w3.org/2001/XMLSchema"
            elementFormDefault="qualified">

    <xs:element name="table">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="name" type="xs:string"/>
                <xs:element name="comments" type="xs:string" minOccurs="0"/>
                <xs:element name="columns" type="columnsType"/>
                <xs:element name="constraints" type="constraintsType" minOccurs="0"/>
                <xs:element name="indexes" type="indexesType" minOccurs="0"/>
                <xs:element name="data" type="dataType" minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="columnType">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="type" type="xs:string"/>
            <xs:element name="mandatory" type="xs:boolean" minOccurs="0"/>
            <xs:element name="primary" type="xs:boolean" minOccurs="0"/>
            <xs:element name="comments" type="xs:string" minOccurs="0"/>
            <xs:element name="defaultValue" type="xs:string" minOccurs="0"/>
            <xs:element name="foreign" type="foreignType" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="constraintType">
        <xs:sequence>
            <xs:element name="constraintName" type="xs:string"/>
            <xs:element name="sqlExpression" type="sqlExpressionType"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="indexType">
        <xs:sequence>
            <xs:element name="name" type="xs:string"/>
            <xs:element name="unique" type="xs:boolean"/>
            <xs:element name="sqlExpression" type="sqlExpressionType"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="indexesType">
        <xs:sequence>
            <xs:element name="index" type="indexType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="columnsType">
        <xs:sequence>
            <xs:element name="column" type="columnType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="constraintsType">
        <xs:sequence>
            <xs:element name="constraint" type="constraintType" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>
    
    <xs:simpleType name="sqlExpressionType">
        <xs:restriction base="xs:string"/>
    </xs:simpleType>

    <xs:complexType name="foreignType">
        <xs:sequence>
            <xs:element name="foreignTableName" type="xs:string"/>
            <xs:element name="foreignTabColumnName" type="xs:string"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="dataType">
        <xs:sequence>
            <xs:element name="values" type="xs:string" minOccurs="1" maxOccurs="unbounded"/>
        </xs:sequence>
    </xs:complexType>


</xs:schema>

=== sevastyanovii/glnew-sql4/SQL/TABLES/OPERATION.xml
<?xml version="1.0" encoding="windows-1251"?>
<table xmlns="www.sqlpatchbuilder.org/table"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="www.sqlpatchbuilder.org/table ../../xsd/table-definition.xsd">
    <name>OPERATION</name>
    <comments>Таблица для регистрации операции GL - первичной информации для последующего формирования проводок GL</comments>
    <columns>
        <column>
            <name>AC_POS_DR</name>
            <type>VARCHAR2(20 CHAR)</type>
            <comments>Счет валютной позиции для дебетовой стороны операции</comments>
        </column>
        <column>
            <name>AC_POS_EQV_DR</name>
            <type>VARCHAR2(20 CHAR)</type>
            <comments>Счет эквивалента валютной позиции для дебетовой стороны операции</comments>
        </column>
        <column>
            <name>AC_POS_CR</name>
            <type>VARCHAR2(20 CHAR)</type>
            <comments>Счет валютной позиции для кредитовой стороны операции</comments>
        </column>
        <column>
            <name>AC_POS_EQV_CR</name>
            <type>VARCHAR2(20 CHAR)</type>
            <comments>Счет эквивалента валютной позиции для кредитовой стороны операции</comments>
        </column>
        <column>
            <name>FCYBC_EQV_AMNT</name>
            <type>NUMBER(19,3)</type>
            <comments>Локальный эквивалент суммы базовой валют по курсу ЦБ на дату операции</comments>
        </column>
        <column>
            <name>EXCН_DIFF</name>
            <type>NUMBER(19,3)</type>
            <comments><![CDATA[Курсовая разница от валютообменной операции, >0 для положительной, <0 для отрицательной]]></comments>
        </column>
        <column>
            <name>BRANCH_DR</name>
            <type>CHAR(3 CHAR)</type>
<!--        TODO в ФСД обязательное поле    <mandatory>true</mandatory>-->
            <comments>Бранч  FC, в котором открыт счет дебета AC_DR</comments>
        </column>
        <column>
            <name>BRANCH_CR</name>
            <type>CHAR(3 CHAR)</type>
<!--         TODO в ФСД обязательное поле   <mandatory>true</mandatory>-->
            <comments>Бранч  FC, в котором открыт счет дебета AC_DR</comments>
        </column>
        <column>
            <name>BANK_ID_DR</name>
            <type>CHAR(5 CHAR)</type>
<!--            TODO в ФСД обязательное поле <mandatory>true</mandatory>-->
            <comments>МФО Банка, в котором открыт счет дебета AC_DR</comments>
        </column>
        <column>
            <name>BANK_ID_CR</name>
            <type>CHAR(5 CHAR)</type>
<!--          TODO в ФСД обязательное поле   <mandatory>true</mandatory>-->
            <comments>МФО Банка, в котором открыт счет кредита AC_DR</comments>
        </column>
    </columns>
</table>

=== sevastyanovii/glnew-sql4/SQL/TABLES/ACC.xml
<?xml version="1.0" encoding="windows-1251"?>
<table xmlns="www.sqlpatchbuilder.org/table"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="www.sqlpatchbuilder.org/table ../../xsd/table-definition.xsd">
    <name>ACC</name>
    <comments>Банковский счет</comments>
    <columns>
        <column>
            <name>POSTYPE</name>
            <type>CHAR(3 CHAR)</type>
            <comments>Признак счета валютной позиции (POS) или счета эквивалента валютной позиции (EQV)</comments>
        </column>
        <column>
            <name>CCY_POS</name>
            <type>CHAR(3 CHAR)</type>
            <comments>Буквенный код валюты валютной позиции</comments>
        </column>
    </columns>
    <constraints>
        <constraint>
            <constraintName>CH_ACC_POSTYPE</constraintName>
            <sqlExpression>CHECK (POSTYPE IN ('POS','EQV'))</sqlExpression>
        </constraint>
    </constraints>
</table>
